import os
import asyncio
from crewai import Agent, Task, Crew, LLM

def create_startup_crew(api_key: str, repo_url: str, repo_description: str) -> Crew:
    # إعداد الاتصال بالسيرفر
    fireworks_llm = LLM(
        model="fireworks_ai/accounts/fireworks/models/deepseek-v3p1",
        base_url="https://api.fireworks.ai/inference/v1",
        api_key=api_key,
        temperature=0.3
    )

    # بناء الوكلاء
    repository_auditor = Agent(
        role="Universal Product & Domain Auditor",
        goal="Analyze any given repository link and description to discover its business niche, industry vertical, and target audience.",
        backstory=(
            "You are an expert venture capitalist and product architect. You can look at any tech startup project—"
            "whether it is a Shopify plug-in, a fintech payment gateway, an AI model, or an e-commerce platform—"
            "and instantly map out who needs this product and why it matters."
        ),
        llm=fireworks_llm,
        verbose=True
    )

    marketing_strategist = Agent(
        role="Growth Marketing Specialist",
        goal="Take the detected domain profile and generate highly converting social media launch copy specifically tailored to that market audience.",
        backstory=(
            "You are a growth hacking marketer. If the auditor says the project is E-commerce, you write high-energy sales copy. "
            "If it is a technical tool, you write deep dev-focused engineering copy. You adapt your tone completely based on the audience."
        ),
        llm=fireworks_llm,
        verbose=True
    )

    # تحديد المهام
    task_detect_everything = Task(
        description=(
            f"Examine the following repository details:\n"
            f"- URL: {repo_url}\n"
            f"- User Description: {repo_description}\n\n"
            "Identify the industry sector (e.g., E-commerce, EdTech, SaaS, AI, DevOps). "
            "Define the exact ideal customer profile (ICP) who would buy or use this startup project."
        ),
        expected_output="A complete product profile specifying the detected industry vertical and target buyer persona.",
        agent=repository_auditor
    )

    task_tailor_marketing = Task(
        description=(
            "Review the product profile generated by the Auditor. Based on the specified industry vertical, "
            "draft 2 launch posts (LinkedIn and X) that directly speak to that audience's pain points. "
            f"Make sure to naturally include the repository link: {repo_url}"
        ),
        expected_output="Two tailored marketing copy assets optimized for the specific target industry.",
        agent=marketing_strategist
    )

    # تجميع الـ Crew
    return Crew(
        agents=[repository_auditor, marketing_strategist],
        tasks=[task_detect_everything, task_tailor_marketing],
        verbose=True
    )